services:
  postgres:
    image: postgres:17
    container_name: finanzas-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgre@admin123
      POSTGRES_DB: finanzas_personales
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: